from openbot.abstract.function import FunctionBase
import openbot.permissions as perms
import openbot.config as config


class BotFunction(FunctionBase):
  """
  Stub file for jhnhnck_coreftns/chat_bind.py
  Auto-generated by discord-bot-core on 2017-02-19 12:11:28.351458
  """


  def load_test(self):
    """
    Loading Self Test.
    Implement this method to allow for more vigorous control over loading requirements.

    Returns:
      Dictionary with two keys:
        state: True if the function should be loaded
        msg: Detailed error message (Do not use logging here; It may not always work)
    """
    return {'state': True}


  def call(self, client, message, mod):
    """
    Call.
    Binds the discord bot to a specific channel
    """
    # has_permission will handle no permissions
    if perms.has_permission(message.owner, 'admin.set_channel_bindings'):
      if mod.get('--append'):
        channel_ids = config.get_config('chant.channels.bind_text_channels')
        channel_ids = channel_ids.append(message.channel.id)
      else:
        channel_ids = [message.channel.id]

      config.set_config('chant.channels.bind_text_channels', channel_ids)
